# Generated by Django 5.1.7 on 2025-03-08 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="eta",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
